spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:producer, consumer}

---
  #'consumer' profile only
spring:
  config:
    activate:
      on-profile: consumer
  kafka:
    template:
      default-topic: ${KAFKA_DEFAULT_TOPIC:topic}
    consumer:
      bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
      group-id: group_id
      auto-offset-reset: earliest
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

---
#'producer' profile only

spring:
  config:
    activate:
      on-profile: producer
  kafka:
    template:
      default-topic: ${KAFKA_DEFAULT_TOPIC:topic}
    producer:
      bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: message:com.pilot.springbootkafkaproducerconsumer.model.Message, sms:com.pilot.springbootkafkaproducerconsumer.model.Sms

server:
  port: 9000

springdoc:
  api-docs:
    path: /api-docs

---